name: Build and Deploy Angular Web App to Nginx

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    paths:
      - 'web/**'  # Adjust path to match your Angular project folder
    branches:
      - master

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'  # Your specified Node.js version

      - name: Install Dependencies
        run: |
          cd web
          npm ci  # Ensures a clean and reproducible install

      - name: Build Angular App
        run: |
          cd web
          npm run build -- --configuration=production

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Web_Build
          path: dist/web 

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: Web_Build
          path: /home/runner/web-build

      - name: Deploy to Nginx Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "/home/runner/web-build/*"
          target: "/var/www/html/web"  # Adjust based on your Nginx setup
          strip_components: 3
          rm: true  # Removes old files before uploading

      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            systemctl restart nginx

      - name: Cleanup Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: Web_Build
